general.import = [
    "~/.config/alacritty/themes/themes/challenger_deep.toml"
]
general.live_config_reload = true

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.85
option_as_alt = "Both"
startup_mode = "SimpleFullscreen"
padding = { x = 10, y = 10 }

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Command|Shift" }
regex = "(mailto:|https:|http:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "K"
mods = "Command"
action = "ClearHistory"

[[keyboard.bindings]]
key = "F"
mods = "Control|Command"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"
